### PR TITLE
Add PEDIGREE header parsing

### PR DESCRIPTION
**Pull request by anderspitman**
Also fixed to be able to handle empty Description fields

### CODE REVIEW

**Comment by ihodes** [comment]
This looks good, thanks for the fix & feature!

**Comment by anderspitman** [comment]
No problem, thanks for the quick merge. What's your deployment flow for getting new versions on NPM? I may have some additional changes for you to look at in the near future, but don't know yet.

**Comment by ihodes** [comment]
>  What's your deployment flow for getting new versions on NPM?

Good question; I haven't done that for a while: I'll deploy the new version tomorrow and document it!

> I may have some additional changes for you to look at in the near future, but don't know yet.

Excellent! Changes definitely welcome :)

**Comment by ihodes** [comment]
New version is published as 0.3.0

**Pull request merged**
